@startuml
title Process - Containers

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary("Process_boundary", "Process") {
  Container(Process.Motivation, "Motivation", "a reason for actions, willingness, and goals", $tags="Element+Container")
  Container(Process.Action, "Action", "a behavior caused by an agent in a particular situation", $tags="Element+Container")
  Container(Process.Result, "Result", "the change occuring to a system after an action has been performed", $tags="Element+Container")
  Container(Process.Observation, "Observation", "the change occuring to a system after an action has been performed", $tags="Element+Container")
}

Rel_D(Process.Motivation, Process.Action, "drives", $tags="Relationship")
Rel_D(Process.Action, Process.Result, "influences", $tags="Relationship")
Rel_D(Process.Observation, Process.Result, "interpretation of", $tags="Relationship")

SHOW_LEGEND()
@enduml