@startuml
title Linguistic - System Context

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

System(Linguistic, "Linguistic", "A system of signs governed by grammatical rules of combination to communicate meaning", $tags="Element+Software System")
Person(KnowledgeAgregator, "Knowledge Agregator", "An agent synthesising nuggets from disjointed observations.", $tags="Element+Person")

Rel_D(KnowledgeAgregator, Linguistic, "formulates thoughts using", $tags="Relationship")

SHOW_LEGEND()
@enduml