title: Pragmatic Penguin Patterns
baseURL: "localhost:1313"


module:
  imports:
    path: github.com/StefMa/hugo-fresh

assetDir: "assets"
enableRobotsTXT: true

paginate: 5
canonifyURLs: true

# Disables warnings
markup:
  defaultMarkdownHandler: goldmark
  highlight:
    codeFences: true
    noClasses: true
    lineNos: false
    style: catppuccin-frappe
    guessSyntax: true
    tabWidth: 2
  goldmark:
    extensions:
      footnote: true
    renderer:
      unsafe: true # Allows you to write raw html in your md files

taxonomies:
  category: "categories"
  tag: "tags"
  level: "levels"

params:
  dataDir: /data
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Designed to share valuable insights and best practices with kdnowledge workers. Covering a range of topics from cognitive biases to pattern-based knowledge sharing, it combines personal experiences with curated resources to help navigate the complexities of software development.
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/ppp_logo.png
    link: "/"
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Pragmatic Penguin Pattern Portfolio
    # Hero subtitle (optional)
    subtitle: Become a better (software) professional, by standing on the shoulders of giants
    # Button text
    buttontext: Start Reading
    # Where the main hero button links to
    buttonlink: "#introduction"
    # Hero image (from static/images/___)
    image: penguin_learning
    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
    clientlogos:

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Approach
    url: /about
  - title: Concepts
    url: /concepts/
  - title: Practices
    url: /practices/
  - title: Resources
    sublinks:
      - title: Glossary
        url: /glossary/
      - title: Bibliography
        url: /books
      - title: "Tools, Websites, Apps"
        url: /tools/
  - title: Admin
    sublinks:
      - title: Change Log
        url: /changelog/
      - title: License
        url: /license/

  section1:
    title: Making sense of advice
    subtitle: the trouble with "best practices" is they never seem to work
    text: >
      We tend to learn a great deal about a wide variety of topics. Yet, from time to time, we are stumped by how elegantly or easily
      someone solves a certain problem. You are left wondering why you have not been tackling similar problems in the same way. It could have saved you
      vast amounts of frustration if only you had known earlier. <br />
      Why did you not know? Why did you not see the solution? Why did you not apply the same technique? 
      <br /><br />
      The answer is simple: you did not know it existed.  
      <br />No one told you about it. No one shared their knowledge with you.  
      <br />Or maybe they did, but you did not understand it. Or you did not see the value in it.
      <br /><br />
      Sharing knowledge can be challenging because people often speak different "languages" when it comes to ideas. 
      Using a structured approach helps us better express and understand concepts, but how do we make sense of the countless frameworks and practices that exist?
      <br /><br />
      And even if we do understand them, how do we know when to apply them? After all, not every tool is right for every job. You are unique, your situation is unique, and so should be your approach.
      <br /><br />
      That's where we come in.<br /> 
      This knowledge base will help you make sense of the vast amount of information out there, so you can focus on what matters most to you.
  section2:
    title: Yet another framework?
    subtitle: Not quite. Here's what makes us different.
    image: sense_making_meta_model
    features:
    - title: Focus on practical use
      text: Rather than stick to theory, we aim to help you put what you learn into effect as quickly as possible. By focussing on when techniques and ideas are valuable, you will understand when to apply an idea. And more importantly, when not to apply it.
    - title: Terminology explained
      text: The amount of jargon used when discussing specialized techniques and technology can be overwhelming to newcomers. This publication helps you get acquainted with them so you know what people are talking about.
    - title: Resources & Background information
      text: Recommended background reading, in case you want to dig deeper into certain topics. As with all content here, we focus on showing what is in it for you.
  section3:
    title: Learn. Grow. Improve.
    subtitle: discover new ideas and techniques to help you excel
    text: >
      Imagine the thrill of discovering new ideas and techniques that will help you excel at the things you do every day.
      Whether you're already working in a technical role or just starting out, there's always more to learn and explore.
      Either way, we've got something for you.  
      <br />  
      
      In this knowledge base, you'll discover practical insights and valuable tips from experts who have dedicated themselves to mastering their craft.
      By reading on, you'll gain a deeper understanding of the topics that interest you and learn new ways to take steps towards achieving your goals and
      becoming the best you can be.    
      <br />
      <br />
      
      So why not give it a try? Dive in and see how far you can go.
    links:
      - text: Concepts
        link: "/concepts"
#      - text: Pillars
#        link: "/pillars"
      - text: Practices
        link: "/practices"

  footer:
    # Logo (from /images/logos/___)
    logo: logo_trans_border_scaled.webp
    # Social Media Title
    socialmediatitle: Socials
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/sddevelopment-be/penguin-pragmatic-patterns
      # Icons are from Font Awesome
      icon: github
    - link: https://www.linkedin.com/company/sddevelopment-be
      # Icons are from Font Awesome
      icon: linkedin
    bulmalogo: false
    quicklinks:
      column1:
        title: "Main Content"
        links:
          - text: Approach
            link: /about
          - text: Practices
            link: /practices
          - text: Concepts
            link: /concepts
      column2:
        title: "Resources"
        links:
        - text: Glossary
          link: /glossary
        - text: Bibliography
          link: /books
        - text: "Tools, Websites, Apps"
          link: /tools
      column3:
        title: "Admin"
        links:
        - text: Change Log
          link: /changelog
        - text: License
          link: /license

mediaTypes:
  text/enriched:
    suffixes:
      - enr
  text/html:
    suffixes:
      - asp
      - html
      - htm
  application/xml:
    suffixes:
     - xml
  application/rss+xml:
    suffixes:
      - rss
  application/json:
    suffixes:
      - json
  application/yaml:
    suffixes:
      - yaml
      - yml

#outputFormats:
#  xml:
#    mediaType: application/xml
#  html:
#    mediaType: text/html
#  rss:
#    mediaType: application/rss+xml
#  json:
#    mediaType: application/json
#  yaml:
#    mediaType: application/yaml

## Integrations and services
services:
  rss:
    limit: 42

author:
  email: stijn@sddevelopment.be
  name: Stijn Dejongh
copyright: © 2023 SD Development, BV.

defaultContentLanguage: en
defaultContentLanguageInSubdir: false
languages:
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ""
    languageName: "English"
    title: ""
    weight: 0
  nl:
    contentDir: content/nl
    disabled: false
    languageCode: nl-BE
    languageDirection: ""
    languageName: "Nederlands"
    title: ""
    weight: 1
    params:
      navbar:
        - title: Aanpak
          url: /nl/about
        - title: Concepten
          url: /nl/concepts/
        - title: Methodes
          url: /nl/practices/
        - title: Hulpmiddelen
          sublinks:
            - title: Woordenlijst
              url: /nl/glossary/
            - title: Bibliografie
              url: /nl/books
            - title: "Tools, Websites, Apps"
              url: /nl/tools/
        - title: Admin
          sublinks:
            - title: Aanpassingsoverzicht
              url: /nl/changelog/
            - title: Licentie
              url: /nl/license/