"base_path": "."
"base_url": "https://api.crowdin.com"

#
# Choose file structure in Crowdin
"preserve_hierarchy": true

files: [
  {
    "source": "/content/en/**/*.md",
    "translation": "/content/%two_letters_code%/**/%original_file_name%",
    "ignore": ["/**/%two_letters_code%/*", "*TEMPLATE*"],
  },
  {
    "source": "/content/en/*.md",
    "translation": "/content/%two_letters_code%/%original_file_name%",
    "ignore": [ "/%two_letters_code%/*", "*TEMPLATE*" ],
  },
  {
    "source": "/data/*",
    "translation": "/data/%file_name%_%two_letters_code%.%file_extension%",
    "ignore": [ "/data/*_nl.*" ],
  }
]