baseURL: http://something-fresh.org/
languageCode: en-us
title: Pragmatic Penguin Patterns

module:
  # uncomment line below for local development of module
  # workspace: hugo.work
  imports:
    path: github.com/StefMa/hugo-fresh

googleAnalytics: # Put in your tracking code without quotes like this: UA-XXX for universal tracking or G-XXX analytics v4 tracking
# Disables warnings
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

taxonomies:
  category: categories
  tag: tags

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/ppp_logo.png
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Pragmatic Penguin Pattern Portfolio
    # Hero subtitle (optional)
    subtitle: Become a better software professional, by standing on the shoulders of giants
    # Button text
    buttontext: Start Reading
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
    clientlogos:

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About
    url: /
  - title: Concepts
    url: /concepts/
  - title: Practices
    url: /practices/
  - title: Glossary
    url: /glossary/
  - title: Resources
    sublinks:
      - title: long form
        url: /
      - title: short form
        url: /
      - title: tools
        url: /
      - title: bibliography
        url: /
  - title: Start reading
    url: /chapters/intro
    button: true

  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  footer:
    # Logo (from /images/logos/___)
    logo: ppp_logo_light.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/sddevelopment-be/penguin-pragmatic-patterns
      # Icons are from Font Awesome
      icon: github
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
