@startuml
title Experimental - Containers

left to right direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System(Beliefs, "Beliefs", "a rule-based system used to reason, structure, and abstract", $tags="Element+Software System+mind")

System_Boundary("Experimental_boundary", "Experimental") {
  Container(Experimental.drivers, "drivers", "", $tags="Element+Container")
  Container(Experimental.inspection, "inspection", "", $tags="Element+Container")
  Container(Experimental.process, "process", "", $tags="Element+Container")
  Container(Experimental.entities, "entities", "", $tags="Element+Container")
}

Rel_D(Experimental.inspection, Experimental.entities, "performed on", $tags="Relationship")
Rel_D(Experimental.drivers, Experimental.process, "reason for", $tags="Relationship")
Rel_D(Experimental.drivers, Experimental.entities, "based on perception of", $tags="Relationship")
Rel_D(Experimental.process, Experimental.entities, "induces potential change in", $tags="Relationship")
Rel_D(Experimental.process, Experimental.inspection, "is reference for", $tags="Relationship")
Rel_D(Experimental.inspection, Experimental.drivers, "input for", $tags="Relationship")
Rel_D(Beliefs, Experimental.inspection, "originates from", $tags="Relationship")

SHOW_LEGEND()
@enduml