@startuml
title Experimental - inspection - Components

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System(Beliefs, "Beliefs", "a rule-based system used to reason, structure, and abstract", $tags="Element+Software System+mind")
Container(Experimental.process, "process", "", $tags="Element+Container")
Container(Experimental.drivers, "drivers", "", $tags="Element+Container")
Container(Experimental.entities, "entities", "", $tags="Element+Container")

Container_Boundary("Experimental.inspection_boundary", "inspection") {
  Component(Experimental.inspection.Observation, "Observation", "perceiving something, such as a phenomenon, often by means of an instrument, and making a record of the resulting information", $tags="Element+Component")
  Component(Experimental.inspection.Assessment, "Assessment", "to evaluate the worth, significance, or status of", $tags="Element+Component")
}

Rel_D(Experimental.inspection.Observation, Experimental.process, "interpretation of", $tags="Relationship+domain")
Rel_D(Experimental.inspection.Observation, Experimental.entities, "performed on", $tags="Relationship")
Rel_D(Experimental.inspection.Assessment, Experimental.inspection.Observation, "based on data from", $tags="Relationship+domain")
Rel_D(Experimental.drivers, Experimental.process, "reason for", $tags="Relationship")
Rel_D(Experimental.drivers, Experimental.entities, "based on perception of", $tags="Relationship")
Rel_D(Experimental.process, Experimental.entities, "induces potential change in", $tags="Relationship")
Rel_D(Experimental.process, Experimental.inspection.Assessment, "is reference for", $tags="Relationship")
Rel_D(Experimental.inspection.Assessment, Experimental.drivers, "input for", $tags="Relationship")
Rel_D(Experimental.entities, Experimental.process, "performs", $tags="Relationship+domain")
Rel_D(Beliefs, Experimental.inspection.Observation, "originates from", $tags="Relationship")

SHOW_LEGEND()
@enduml