@startuml
title Experimental - process - Components

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(Experimental.drivers, "drivers", "", $tags="Element+Container")
Container(Experimental.inspection, "inspection", "", $tags="Element+Container")
Container(Experimental.entities, "entities", "", $tags="Element+Container")

Container_Boundary("Experimental.process_boundary", "process") {
  Component(Experimental.process.Result, "Result", "the change occuring to a system after an action has been performed", $tags="Element+Component")
  Component(Experimental.process.Action, "Action", "a behavior caused by an agent in a particular situation", $tags="Element+Component")
  Component(Experimental.process.Objective, "Objective", "the object of one's endeavours; the intended change to be achieved. aka. 'goal', 'aim', 'target', 'expectation'", $tags="Element+Component")
}

Rel_D(Experimental.inspection, Experimental.process.Result, "interpretation of", $tags="Relationship+domain")
Rel_D(Experimental.inspection, Experimental.entities, "performed on", $tags="Relationship")
Rel_D(Experimental.drivers, Experimental.process.Objective, "reason for", $tags="Relationship")
Rel_D(Experimental.drivers, Experimental.entities, "based on perception of", $tags="Relationship")
Rel_D(Experimental.process.Objective, Experimental.inspection, "is reference for", $tags="Relationship")
Rel_D(Experimental.inspection, Experimental.drivers, "input for", $tags="Relationship")
Rel_D(Experimental.entities, Experimental.process.Action, "performs", $tags="Relationship+domain")
Rel_D(Experimental.process.Action, Experimental.process.Result, "influences", $tags="Relationship+domain")
Rel_D(Experimental.process.Objective, Experimental.process.Action, "instigates", $tags="Relationship+domain")

SHOW_LEGEND()
@enduml