@startuml
'https://plantuml.com/sequence-diagram

!include ../doc_templates/plantuml/puml-theme-bluegray_conversation.puml
skinparam dpi 320
skinParam maxMessageSize 280
hide stereotype
hide footbox

<style>
    sequenceDiagram {
        FontSize 12
        Font monospaced
        BackgroundColor #0c141a

        participant {
            BackGroundColor #1c75cc/1541CC
        }

        responder {
            BackGroundColor #63CC4A/349646
        }

        arrow {
            FontColor #1c75cc
        }

        .reply * {
            FontColor #63CC4A/349646
        }

        note {
            FontSize 10
            BackgroundColor #1D1B1B
        }

    }
</style>

participant Alex as A
participant Bernie as B <<responder>> #63CC4A/349646

note over A, B: Alex and Bernie are part of a remote-first team

A -> B : Hello, Bernie. I'd like your help in figuring out how to restart the development back-end server. \n\nWe are trying to resolve an issue caused by a misconfiguration of the application. I have alreadt fixed the config, but can not figure out how to restart the server.\n\nAs it stands, the team can not perform their integration tests, so we need this solved by 12:30.

rnote over B:  Sees message. \nStops working.\nLooks at clock, and sees it is 10:00.
rnote over B:  Estimates the restart will take about 45 minutes to perform.\nFinishes what they were doing.

B -> A <<reply>> : Hey Alex. Sounds like you are doing what I would have done.\nYou could first try to reset the application's internal cache, that takes about 5 minutes to complete, a server restart takes about 45 minutes.\n\n \nWe have a page on resetting the config caches here: http://teamname.internal-wiki.org/reset-caches.\n\nThe approach to restart the servers is documented here: http://teamname.internal-wiki.org/restart-servers
B -> A <<reply>> : If you get stuck, feel free to reach out. But do so before 11:15 if possible, so I can accomodate.

A -> B : Great! Thanks, Bernie. I'll try and see if the documentation helps me, and will get back to you before 11:00.

rnote over A:  Tries to reset the caches.\nThis indeed solves the problem.

A -> B : I tried the cache reset first, and that has indeed solved the problem. Thanks again for helping us out!

@enduml