@startuml

skinparam dpi 164

skinparam maxMessageSize 184
skinparam wrapWidth 204

skinparam shadowing true

<style>
activityDiagram {
  BackgroundColor #33668E
  BorderColor #33668E
  LineColor #DarkSlateGrey
  FontColor #fefefe
  FontName arial

  diamond {
    BackgroundColor #ccf
    FontName arial
    FontSize 15
  }
  arrow {
    FontColor OldLace
    LineColor OldLace
    FontName arial
    FontSize 15
  }
  partition {
    LineColor red
    FontColor green
    RoundCorner 10
    BackgroundColor PeachPuff
  }
  note {
    FontColor Blue
    LineColor Navy
    BorderColor #33668E
    BackgroundColor #ccf
  }
}
document {
   BackgroundColor transparent
}
</style>

|#MidnightBlue| Vision |
	:Goal;
|#DarkSlateBlue| Approach |
	:Strategy;
	:Tactics;
|#SteelBlue| Realization |
	:Execution;
	:Result;
	:Rollout;
	:Follow-up;
stop

@enduml