@startuml
title "Chain of Accountability"

top to bottom direction

!include ../templates/plantuml/puml-theme-bluegray.puml

skinparam dpi 280

skinparam maxMessageSize 184
skinparam wrapWidth 204

skinparam shadowing true

<style>
' had to override this here as the included theme was not working properly
classDiagram {
  class {
      ' class name
      header {
        FontColor #dedede
        FontSize 12
        FontStyle bold
      }
  }
}
</style>

hide stereotype
hide circle

class "Goal" #Darkorange {}
class "Strategy" #DarkSlateBlue {}
class "Tactics" #DarkSlateBlue {}
class "Execution" #DarkSlateBlue {}
class "Result" {}
class "Rollout" #DarkSlateGrey {}
class "Follow-up" #DarkSlateGrey {}

"Goal" -> "Strategy"
"Strategy" -> "Tactics"
"Tactics" -> "Execution"
"Execution" -> "Result"
"Result" -> "Rollout"
"Rollout" -> "Follow-up"

@enduml