@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

<style>
activityDiagram {
  BackgroundColor #0290e8
  BorderColor #171c26
  FontName arial
  FontColor #fefefe
  LineColor #171c26

  diamond {
    BackgroundColor #171c26
    LineColor #0290e8
    FontColor #fefefe
    FontName arial
    FontSize 15
  }
  arrow {
    FontColor #171c26
    FontName arial
    FontSize 15
  }
  partition {
    LineColor #0290e8
    FontColor #fefefe
    RoundCorner 10
    BackgroundColor #1f2532
  }
  note {
    FontColor #0290e8
    LineColor Navy
    BackgroundColor #22272e
  }
}
document {
   BackgroundColor transparent
}
</style>

'' Diagram starts here

title The `OPERAS´ mental model for goal achievement

start

#orange:**TODO**;
repeat :**O**rientate;
  :**P**repare;
  repeat :**E**xecute;
    :**R**eflect;
    :**A**dapt;
  backward:Try to complete substep if still feasible;
  repeat while (substep completed?) is (no)
  ->yes;
backward:What is next?;
repeat while (milestone reached?) is (no)
->yes;
:**S**ynthesize;
if(share with others?) then (yes)
  #175574:Document findings for target audience;
else (no)
endif
->no;
#green:**DONE** for now;
stop
@enduml
