@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

left to right direction

skinparam linetype polyline
skinparam dpi 320
skinparam wrapWidth 260

hide stereotype

Boundary("SoftDev", "Section: Software Development") {

    Container(SoftDev.Patterns, "Patterns", "", "") {
          Component(SoftDev.Concepts, "Concepts", "", "Higher level concepts, in a more free format style")
          Component(SoftDev.Practices, "Practices", "", "Structured motifs documenting approaches that have worked well in the past")
    }

    Container(SoftDev.Supporting, "Supporting material", "", "") {
        Component(SoftDev.Articles, "Articles", "", "A selection of articles and blog posts related to working as a software developer")
        Component(SoftDev.Tutorials, "Tutorials", "", "Deep-dive learning materials, in course/tutorial format.")
        Component(SoftDev.Resources, "Resources", "", "Lists, diagrams, reviews, code snippets, and the likes")
    }

    SoftDev.Patterns -[hidden]-> SoftDev.Supporting

}


@enduml
