@startuml
title System Landscape

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

System(Social, "Social", "a patterned network of relationships constituting a coherent whole that exist between individuals, groups, and institutions", $tags="Element+Software System+people")
System(Experimental, "Experimental", "a system in which actions take place and observations are made", $tags="Element+Software System+science")
System(Beliefs, "Beliefs", "a rule-based system used to reason, structure, and abstract", $tags="Element+Software System+mind")
System(Linguistic, "Linguistic", "A system of signs governed by grammatical rules of combination to communicate meaning", $tags="Element+Software System+communication")
Person(KnowledgeAgregator, "Knowledge Agregator", "An agent synthesising nuggets from disjointed observations.", $tags="Element+Person")

Rel_D(KnowledgeAgregator, Linguistic, "formulates thoughts using", $tags="Relationship")
Rel_D(KnowledgeAgregator, Beliefs, "lives, operates, and thinks based on a personal", $tags="Relationship")
Rel_D(KnowledgeAgregator, Experimental, "operates as an actor within", $tags="Relationship")
Rel_D(KnowledgeAgregator, Social, "is part of one or more", $tags="Relationship")

SHOW_LEGEND()
@enduml